language: node_js

dist: trusty

sudo: required

node_js:
- '10.15.1'

cache:
  directories:
    - node_modules

# safelist of branches to build
branches:
  only:
  - master

git:
  submodules: true

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - npm i -g npm@6.4.1
  - npm install
#   - npm run postinstall
  - npm run build

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm run knex:migrate
  - npm run knex:seed
  - npm run test:server
  - npm run e2e

# after_success:

notifications:
  email:
    recipients:
      - $EMAIL_ADMIN
    # always|never|change - change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
